################################################################################
# Behavior
################################################################################

# keep a large history
set -g history-limit 200000

# monitor bells in windows (explicit attention signals from programs)
setw -g monitor-bell on
setw -g monitor-activity off

# use vim motion keys while in copy mode
setw -g mode-keys vi

# set base window and pane indices to 1
set -g base-index 1
setw -g pane-base-index 1

# my terminal has all these colors!
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# renumber windows when one is closed
set -g renumber-windows on

# preserve setting of window names
set -g allow-rename off

# shorten command delay
set -sg escape-time 0

# make window resizing better between multiple clients
setw -g aggressive-resize on

# enable OSC-8 hyperlinks
set -as terminal-features ",*:hyperlinks"
