################################################################################
# Setup
################################################################################

tmux_dir="~/.config/tmux"
tmux_conf_dir="$tmux_dir/config"

################################################################################
# Configuration
################################################################################

source "$tmux_conf_dir/options.conf"
source "$tmux_conf_dir/keybindings.conf"
source "$tmux_conf_dir/theme.conf"